# Generated by Django 3.0.4 on 2020-03-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('has_faver', models.BooleanField(default=False)),
                ('fever', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySympton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CovidContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RiskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codeDocumentType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usersProfile', to='core.City')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sympton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptoms', to='core.CategorySympton')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAnalisy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risksAnalisy', to='core.Analisy')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diseases', to='core.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('typeProfessional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional', to='core.TypeProfessional')),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='professional', to='core.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='healthsCenter', to='core.City')),
                ('latLng', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.LatLng')),
                ('listProfessional', models.ManyToManyField(to='core.Professional')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='listSympton',
            field=models.ManyToManyField(to='core.Sympton'),
        ),
        migrations.CreateModel(
            name='DailyNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('underInvestigation', models.IntegerField()),
                ('waiting_exam', models.IntegerField()),
                ('confirmed', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dailyNewsletters', to='core.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='latLng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.LatLng'),
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherRiskGroup', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneMumber', models.CharField(max_length=20)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizens', to='core.City')),
                ('listRiskGroup', models.ManyToManyField(to='core.RiskGroup')),
                ('userProfile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citizen', to='core.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='analisy',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='core.Citizen'),
        ),
        migrations.AddField(
            model_name='analisy',
            name='covidContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='core.CovidContact'),
        ),
        migrations.AddField(
            model_name='analisy',
            name='latLng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.LatLng'),
        ),
        migrations.AddField(
            model_name='analisy',
            name='listSympton',
            field=models.ManyToManyField(to='core.Sympton'),
        ),
    ]
