# Generated by Django 3.0.4 on 2020-03-24 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 17, 44, 35, 841865)),
        ),
    ]
