# Generated by Django 3.0.4 on 2020-03-24 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200324_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
