# Generated by Django 3.0.4 on 2020-03-24 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200324_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='userProfile',
        ),
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='professional', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
