# Generated by Django 3.0.4 on 2020-03-25 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200324_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='latLng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.LatLng'),
        ),
    ]
