# Generated by Django 3.0.4 on 2020-03-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200325_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='listProfessional',
            field=models.ManyToManyField(null=True, to='core.Professional'),
        ),
    ]
