# Generated by Django 3.0.4 on 2020-03-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200325_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='listProfessional',
            field=models.ManyToManyField(blank=True, to='core.Professional'),
        ),
    ]
