# Generated by Django 3.0.4 on 2020-03-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200325_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='listProfessional',
            field=models.ManyToManyField(blank=True, related_name='teste', to='core.Professional'),
        ),
    ]
