# Generated by Django 3.0.4 on 2020-03-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200325_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='listProfessional',
            field=models.ManyToManyField(to='core.Professional'),
        ),
    ]
