# Generated by Django 3.0.4 on 2020-03-25 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200325_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynewsletter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 13, 16, 15, 716961)),
        ),
    ]
