# Generated by Django 3.0.4 on 2020-03-25 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200325_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynewsletter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
