# Generated by Django 3.0.4 on 2020-03-25 17:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200325_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to=core.models.createPathPhotoHealthTips)),
            ],
        ),
    ]
