# Generated by Django 3.0.4 on 2020-03-30 00:55

import core.util_manager
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200329_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postData', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to=core.util_manager.createPathPhotoLogPost)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dailyNewsletters', to='core.City'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='confirmed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='deaths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='recovered',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='underInvestigation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='waiting_exam',
            field=models.IntegerField(),
        ),
    ]
