# Generated by Django 3.0.4 on 2020-03-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200329_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynewsletter',
            name='discarded',
            field=models.IntegerField(default=0),
        ),
    ]
