# Generated by Django 3.0.4 on 2020-03-30 17:42

import core.util_manager
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_dailynewsletter_discarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=core.util_manager.createPathPhotoLogPost, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dailyNewsletters', to='core.City', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='confirmed',
            field=models.IntegerField(verbose_name='Casos Confirmados'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='deaths',
            field=models.IntegerField(verbose_name='Óbitos'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='discarded',
            field=models.IntegerField(verbose_name='Casos Descartados'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='recovered',
            field=models.IntegerField(verbose_name='Casos Curados'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='underInvestigation',
            field=models.IntegerField(verbose_name='Casos Notificados'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='waiting_exam',
            field=models.IntegerField(verbose_name='Casos Aguardando Exame'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='healthsCenter', to='core.City', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='listProfessional',
            field=models.ManyToManyField(to='core.Professional', verbose_name='Profissionais'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='neighborhood',
            field=models.CharField(max_length=255, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='street_number',
            field=models.CharField(max_length=255, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='healthtips',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=core.util_manager.createPathPhotoHealthTips, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='latlng',
            name='lat',
            field=models.CharField(max_length=255, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='latlng',
            name='lng',
            field=models.CharField(max_length=255, verbose_name='Longitude'),
        ),
    ]
