# Generated by Django 3.0.4 on 2020-03-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200331_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='sexo',
            new_name='sex',
        ),
    ]
