# Generated by Django 3.0.4 on 2020-04-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200331_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisy',
            name='fever',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='analisy',
            name='latLng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.LatLng'),
        ),
    ]
