# Generated by Django 3.0.4 on 2020-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_covidcontact_typecontactcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='sex',
            field=models.CharField(blank=True, choices=[['F', 'Feminino'], ['M', 'Masculino']], max_length=1, null=True),
        ),
    ]
