# Generated by Django 3.0.4 on 2020-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200402_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysympton',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='covidcontact',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sympton',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
