# Generated by Django 3.0.4 on 2020-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200408_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailynewsletter',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='underInvestigation',
            field=models.IntegerField(verbose_name='Casos Investigados'),
        ),
    ]
