# Generated by Django 3.0.4 on 2020-04-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200413_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynewsletter',
            name='underInvestigation',
            field=models.IntegerField(verbose_name='Casos em Investigação'),
        ),
    ]
