# Generated by Django 3.0.4 on 2020-04-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200416_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisy',
            name='patient_situation',
            field=models.CharField(default='Sem Situação', max_length=255, verbose_name='Situação do Paciente'),
        ),
        migrations.AddField(
            model_name='analisy',
            name='teleatend_status',
            field=models.CharField(default='Não Iniciado', max_length=255, verbose_name='Status de Teleatendimento'),
        ),
    ]
