# Generated by Django 3.0.4 on 2020-04-19 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200416_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisy',
            name='latLng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='core.LatLng'),
        ),
        migrations.AlterField(
            model_name='analisy',
            name='listSympton',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='core.Sympton'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='listRiskGroup',
            field=models.ManyToManyField(blank=True, related_name='citizens', to='core.RiskGroup'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latLng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='core.LatLng'),
        ),
        migrations.AddIndex(
            model_name='healthcenter',
            index=models.Index(fields=['neighborhood'], name='core_health_neighbo_856382_idx'),
        ),
    ]
