# Generated by Django 3.0.4 on 2020-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200418_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
    ]
