# Generated by Django 3.0.4 on 2020-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200420_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='professional',
            name='firstAcess',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='phoneNumber',
            field=models.CharField(default=0, max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
