# Generated by Django 3.0.4 on 2020-04-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200421_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='firstAcess',
            new_name='firstAccess',
        ),
    ]
