# Generated by Django 3.0.4 on 2020-04-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200421_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynewsletter',
            name='date_publish',
            field=models.DateTimeField(null=True, verbose_name='Data de Publicação'),
        ),
    ]
