# Generated by Django 3.0.4 on 2020-04-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_dailynewsletter_date_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailynewsletter',
            old_name='date_publish',
            new_name='date_publication',
        ),
    ]
