# Generated by Django 3.0.4 on 2020-04-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200422_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailynewsletter',
            options={'ordering': ['-date_publication', '-date']},
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
    ]
