# Generated by Django 3.0.4 on 2020-04-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200422_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-postData']},
        ),
    ]
