# Generated by Django 3.0.4 on 2020-04-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_analisy_othersympton'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='listHealthCenter',
            field=models.ManyToManyField(to='core.HealthCenter', verbose_name='Centros de Saúde'),
        ),
    ]
