# Generated by Django 3.0.4 on 2020-04-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_citizen_listhealthcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='coverage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cobertura'),
        ),
    ]
