# Generated by Django 3.0.4 on 2020-04-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200428_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='listHealthCenter',
        ),
        migrations.AddField(
            model_name='citizen',
            name='healthCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.HealthCenter', verbose_name='Centro de Saúde'),
        ),
        migrations.AlterField(
            model_name='analisy',
            name='latLng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='core.LatLng'),
        ),
    ]
