# Generated by Django 3.0.4 on 2020-05-05 14:48

import core.util_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200429_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, verbose_name='Versão')),
                ('active', models.BooleanField(default=True)),
                ('fileVersion', models.FileField(upload_to=core.util_manager.createPathAppVersion, verbose_name='App')),
            ],
        ),
    ]
