# Generated by Django 3.0.4 on 2020-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20200505_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailynewsletter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthtips',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
