# Generated by Django 3.0.4 on 2020-05-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200506_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailynewsletter',
            old_name='activeStatus',
            new_name='active',
        ),
    ]
