# Generated by Django 3.0.4 on 2020-05-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20200506_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-postDate']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='postData',
            new_name='postDate',
        ),
    ]
