# Generated by Django 3.0.4 on 2020-05-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200507_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city', to='core.City'),
        ),
    ]
