# Generated by Django 3.0.4 on 2020-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200507_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynewsletter',
            name='homeIsolation',
            field=models.IntegerField(default=0, verbose_name='Isolamento Domiciliar'),
        ),
        migrations.AddField(
            model_name='dailynewsletter',
            name='hospitalStay',
            field=models.IntegerField(default=0, verbose_name='Internamento Hospitalar'),
        ),
        migrations.AddField(
            model_name='dailynewsletter',
            name='testsCounty',
            field=models.IntegerField(default=0, verbose_name='Testes Laboratoriais - Município'),
        ),
        migrations.AddField(
            model_name='dailynewsletter',
            name='testsLacen',
            field=models.IntegerField(default=0, verbose_name='Testes Laboratoriais - Lacen'),
        ),
        migrations.AddField(
            model_name='dailynewsletter',
            name='testsPrivate',
            field=models.IntegerField(default=0, verbose_name='Testes Laboratoriais - Privado'),
        ),
    ]
