# Generated by Django 3.0.4 on 2020-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20200602_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynewsletter',
            name='testsCounty',
            field=models.IntegerField(default=0, verbose_name='Exames - Laboratório Municipal'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='testsLacen',
            field=models.IntegerField(default=0, verbose_name='Exames - Lacen Pernambuco'),
        ),
        migrations.AlterField(
            model_name='dailynewsletter',
            name='testsPrivate',
            field=models.IntegerField(default=0, verbose_name='Exames - Particulares'),
        ),
    ]
