# Generated by Django 3.0.4 on 2020-04-10 14:36

import core.util_manager
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_auto_20200408_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats', to='core.Citizen')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats', to='core.Professional')),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_last_modification', models.DateTimeField(auto_now=True, null=True)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='core.Citizen')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='core.Professional')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_last_modification', models.DateTimeField(auto_now=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF')),
                ('sus_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF')),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='core.Citizen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_last_modification', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=core.util_manager.createPathMessageFile, verbose_name='File')),
                ('received', models.BooleanField(default=False)),
                ('is_professional', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='controle_atendimento.Chat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
